# fly.toml file generated for dash007-reactivities on 2023-03-08T22:20:50+01:00

app = "dash007-reactivities"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"
processes = []

[build]
  image = "dash007/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dwalfsenm"
  Cloudinary__ApiKey="171594632278195"


[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
